import sqlite3
import random

connection = sqlite3.connect('db/student_info_system.db')
cursor = connection.cursor()


#cursor.execute('''
#    insert into Students (StudentID,Name,EnrollmentYear,Major,Gender) values (5506100,'akash md',2021,'CS','Male')
#''')

##queries = [
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506101, 'John Doe', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506102, 'Jane Smith', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506103, 'Sam Brown', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506104, 'Chris Johnson', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506105, 'Alex Lee', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506106, 'Jamie Garcia', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506107, 'Taylor White', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506108, 'Morgan Green', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506109, 'Jordan King', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506110, 'Casey Moore', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506111, 'Riley Harris', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506112, 'Skyler Martinez', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506113, 'Peyton Clark', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506114, 'Blake Lewis', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506115, 'Avery Robinson', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506116, 'Quinn Walker', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506117, 'Hayden Hall', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506118, 'Logan Young', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506119, 'Drew Allen', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506120, 'Cameron Scott', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506121, 'Sawyer Adams', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506122, 'Charlie Baker', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506123, 'Dakota Gonzalez', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506124, 'Casey Nelson', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506125, 'Jesse Carter', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506126, 'Jordan Mitchell', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506127, 'Taylor Perez', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506128, 'Morgan Roberts', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506129, 'Peyton Turner', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506130, 'Blake Phillips', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506131, 'Avery Campbell', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506132, 'Quinn Parker', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506133, 'Hayden Evans', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506134, 'Logan Edwards', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506135, 'Drew Collins', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506136, 'Cameron Stewart', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506137, 'Sawyer Morris', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506138, 'Charlie Rogers', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506139, 'Dakota Reed', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506140, 'Casey Cook', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506141, 'Jesse Morgan', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506142, 'Jordan Bell', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506143, 'Taylor Murphy', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506144, 'Morgan Bailey', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506145, 'Peyton Rivera', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506146, 'Blake Cooper', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506147, 'Avery Richardson', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506148, 'Quinn Cox', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506149, 'Hayden Howard', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506150, 'Logan Ward', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506151, 'Drew Brooks', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506152, 'Cameron Watson', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506153, 'Sawyer Hughes', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506154, 'Charlie Flores', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506155, 'Dakota Sanders', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506156, 'Casey Price', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506157, 'Jesse Bennett', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506158, 'Jordan Wood', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506159, 'Taylor James', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506160, 'Morgan Russell', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506161, 'Peyton Ford', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506162, 'Blake Chapman', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506163, 'Avery Butler', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506164, 'Quinn Simmons', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506165, 'Hayden Foster', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506166, 'Logan Gonzales', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506167, 'Drew Bryant', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506168, 'Cameron Alexander', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506169, 'Sawyer Griffin', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506170, 'Charlie Hayes', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506171, 'Dakota Sanders', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506172, 'Casey Butler', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506173, 'Jesse Gonzalez', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506174, 'Jordan Perez', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506175, 'Taylor Rivera', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506176, 'Morgan Long', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506177, 'Peyton Harrison', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506178, 'Blake Stone', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506179, 'Avery Cole', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506180, 'Quinn Harper', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506181, 'Hayden Armstrong', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506182, 'Logan Johnston', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506183, 'Drew Williams', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506184, 'Cameron Baker', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506185, 'Sawyer Adams', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506186, 'Charlie Mitchell', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506187, 'Dakota Phillips', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506188, 'Casey Gray', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506189, 'Jesse Walker', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506190, 'Jordan Scott', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506191, 'Taylor Lewis', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506192, 'Morgan Clark', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506193, 'Peyton Evans', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506194, 'Blake Rodriguez', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506195, 'Avery Harris', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506196, 'Quinn Allen', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506197, 'Hayden Young', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506198, 'Logan Hill', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506199, 'Drew Hernandez', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506200, 'Cameron King', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506201, 'Sawyer Wright', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506202, 'Charlie Lopez', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506203, 'Dakota Hill', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506204, 'Casey Martinez', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506205, 'Jesse Adams', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506206, 'Jordan Wilson', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506207, 'Taylor Perez', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506208, 'Morgan Carter', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506209, 'Peyton Mitchell', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506210, 'Blake Harris', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506211, 'Avery White', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506212, 'Quinn Clark', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506213, 'Hayden Lewis', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506214, 'Logan Walker', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506215, 'Drew Scott', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506216, 'Cameron Hall', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506217, 'Sawyer Allen', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506218, 'Charlie Wright', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506219, 'Dakota Lopez', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506220, 'Casey Hernandez', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506221, 'Jesse King', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506222, 'Jordan Perez', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506223, 'Taylor Carter', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506224, 'Morgan Mitchell', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506225, 'Peyton Harris', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506226, 'Blake White', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506227, 'Avery Clark', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506228, 'Quinn Lewis', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506229, 'Hayden Walker', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506230, 'Logan Scott', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506231, 'Drew Hall', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506232, 'Cameron Allen', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506233, 'Sawyer Wright', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506234, 'Charlie Lopez', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506235, 'Dakota Hernandez', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506236, 'Casey King', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506237, 'Jesse Carter', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506238, 'Jordan Mitchell', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506239, 'Taylor Perez', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506240, 'Morgan Roberts', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506241, 'Peyton Turner', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506242, 'Blake Phillips', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506243, 'Avery Campbell', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506244, 'Quinn Parker', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506245, 'Hayden Evans', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506246, 'Logan Edwards', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506247, 'Drew Collins', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506248, 'Cameron Stewart', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506249, 'Sawyer Morris', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506250, 'Charlie Rogers', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506251, 'Dakota Reed', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506252, 'Casey Cook', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506253, 'Jesse Morgan', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506254, 'Jordan Bell', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506255, 'Taylor Murphy', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506256, 'Morgan Bailey', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506257, 'Peyton Rivera', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506258, 'Blake Cooper', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506259, 'Avery Richardson', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506260, 'Quinn Cox', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506261, 'Hayden Howard', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506262, 'Logan Ward', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506263, 'Drew Brooks', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506264, 'Cameron Watson', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506265, 'Sawyer Hughes', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506266, 'Charlie Flores', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506267, 'Dakota Sanders', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506268, 'Casey Powell', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506269, 'Jesse Long', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506270, 'Jordan Patterson', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506271, 'Taylor Ross', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506272, 'Morgan Jenkins', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506273, 'Peyton Barnes', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506274, 'Blake Fisher', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506275, 'Avery Watts', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506276, 'Quinn Mitchell', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506277, 'Hayden Stevens', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506278, 'Logan Hamilton', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506279, 'Drew Riley', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506280, 'Cameron Hayes', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506281, 'Sawyer Reed', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506282, 'Charlie Diaz', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506283, 'Dakota Bryant', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506284, 'Casey Ramos', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506285, 'Jesse Gonzalez', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506286, 'Jordan Cox', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506287, 'Taylor Perez', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506288, 'Morgan Watson', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506289, 'Peyton Scott', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506290, 'Blake Lewis', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506291, 'Avery Hall', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506292, 'Quinn Allen', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506293, 'Hayden Young', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506294, 'Logan Clark', 2022, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506295, 'Drew Hernandez', 2021, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506296, 'Cameron Martinez', 2020, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506297, 'Sawyer Moore', 2019, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506298, 'Charlie Brown', 2018, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506299, 'Dakota Davis', 2022, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506300, 'Casey Miller', 2021, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506301, 'Jesse Wilson', 2020, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506302, 'Jordan Jackson', 2019, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506303, 'Taylor Anderson', 2018, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506304, 'Morgan Thomas', 2022, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506305, 'Peyton White', 2021, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506306, 'Blake Martinez', 2020, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506307, 'Avery Thomas', 2019, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506308, 'Quinn White', 2018, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506309, 'Hayden Clark', 2022, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506310, 'Logan Hall', 2021, 'EE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506311, 'Drew Moore', 2020, 'ME', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506312, 'Cameron King', 2019, 'CE', 'Female')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506313, 'Sawyer Brown', 2018, 'CS', 'Male')''',
#    '''INSERT INTO Students (StudentID, Name, EnrollmentYear, Major, Gender) VALUES (5506314, 'Charlie Jones', 2022, 'EE', 'Female')'''
#]
#for i in queries :
#    cursor.execute(i)

#cursor.execute('''
# alter table Students
# add column OwnedBooks
# ''')


#cursor.execute('''
#INSERT INTO Teachers (TeacherID,Name,Dept,Gender) VALUES (200,'Jeep mond','Software','Male')
#''')

# queries = [
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (201, 'Alice Smith', 'Mathematics', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (202, 'Bob Johnson', 'Physics', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (203, 'Carol Williams', 'Chemistry', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (204, 'David Brown', 'Biology', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (205, 'Eve Jones', 'English', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (206, 'Frank Garcia', 'History', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (207, 'Grace Martinez', 'Geography', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (208, 'Henry Rodriguez', 'Economics', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (209, 'Ivy Wilson', 'Computer Science', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (210, 'Jack Lee', 'Philosophy', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (211, 'Kathy Harris', 'Political Science', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (212, 'Leo Clark', 'Psychology', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (213, 'Mia Lewis', 'Sociology', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (214, 'Nate Walker', 'Art', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (215, 'Olivia Young', 'Music', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (216, 'Paul King', 'Drama', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (217, 'Quinn Wright', 'Physical Education', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (218, 'Rachel Scott', 'Mathematics', 'Female')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (219, 'Steve Hill', 'Physics', 'Male')''',
# '''INSERT INTO Teachers (TeacherID, Name, Dept, Gender) VALUES (220, 'Tina Green', 'Chemistry', 'Female')'''

# ]

# queries = [

# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (101, 'Introduction to Computer Science', 200)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (102, 'Data Structures and Algorithms', 201)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (103, 'Calculus I', 202)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (104, 'English Literature', 203)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (105, 'World History', 204)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (106, 'General Chemistry', 205)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (107, 'Physics I', 206)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (108, 'Introduction to Psychology', 207)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (109, 'Art History', 208)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (110, 'Music Theory', 209)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (111, 'Introduction to Drama', 210)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (112, 'Physical Education', 211)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (113, 'Advanced Mathematics', 212)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (114, 'Biology I', 213)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (115, 'Macroeconomics', 214)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (116, 'Philosophy of Science', 215)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (117, 'Political Science', 216)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (118, 'Sociology', 217)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (119, 'Creative Writing', 218)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (120, 'Environmental Science', 219)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (121, 'Introduction to Geography', 220)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (122, 'Discrete Mathematics', 221)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (123, 'Software Engineering', 222)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (124, 'Database Systems', 223)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (125, 'Networking', 224)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (126, 'Operating Systems', 225)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (127, 'Artificial Intelligence', 226)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (128, 'Machine Learning', 227)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (129, 'Cybersecurity', 228)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (130, 'Human-Computer Interaction', 229)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (131, 'Quantum Computing', 230)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (132, 'Ethics in Technology', 231)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (133, 'Game Development', 232)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (134, 'Virtual Reality', 233)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (135, 'Augmented Reality', 234)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (136, 'Digital Marketing', 235)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (137, 'Business Analytics', 236)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (138, 'Entrepreneurship', 237)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (139, 'Supply Chain Management', 238)''',
# '''INSERT INTO Courses (CourseID, CourseName, TeacherID) VALUES (140, 'Project Management', 239)'''

# ]

# queries = [

# '''INSERT INTO Books (BookID, Title, Major) VALUES (101, 'Algorithms Unlocked', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (102, 'Introduction to Algorithms', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (103, 'Calculus Made Easy', 'Mathematics')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (104, 'Shakespeare: The Complete Works', 'English')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (105, 'World History: A Comprehensive Guide', 'History')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (106, 'Principles of General Chemistry', 'Chemistry')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (107, 'Fundamentals of Physics', 'Physics')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (108, 'Psychology: An Introduction', 'Psychology')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (109, 'Art Through the Ages', 'Art')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (110, 'Music Theory for Beginners', 'Music')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (111, 'Drama Techniques', 'Drama')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (112, 'Fitness and Health', 'Physical Education')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (113, 'Advanced Mathematics', 'Mathematics')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (114, 'Biology: The Essentials', 'Biology')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (115, 'Economics: Principles and Practices', 'Economics')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (116, 'Philosophy: A Beginner’s Guide', 'Philosophy')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (117, 'Introduction to Political Science', 'Political Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (118, 'Sociology: A Brief Introduction', 'Sociology')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (119, 'Creative Writing Handbook', 'English')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (120, 'Environmental Science', 'Environmental Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (121, 'Geography: A Global Perspective', 'Geography')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (122, 'Discrete Mathematics', 'Mathematics')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (123, 'Software Engineering', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (124, 'Database Systems', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (125, 'Networking Basics', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (126, 'Operating Systems Concepts', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (127, 'Artificial Intelligence', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (128, 'Machine Learning', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (129, 'Cybersecurity Fundamentals', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (130, 'Human-Computer Interaction', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (131, 'Quantum Computing', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (132, 'Ethics in Technology', 'Philosophy')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (133, 'Game Development Essentials', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (134, 'Virtual Reality', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (135, 'Augmented Reality', 'Computer Science')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (136, 'Digital Marketing', 'Business')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (137, 'Business Analytics', 'Business')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (138, 'Entrepreneurship 101', 'Business')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (139, 'Supply Chain Management', 'Business')''',
# '''INSERT INTO Books (BookID, Title, Major) VALUES (140, 'Project Management', 'Business')'''

# ]


# queries = [

# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (101, 130)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (102, 137)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (103, 120)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (104, 139)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (105, 121)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (106, 133)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (107, 128)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (108, 140)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (109, 125)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (110, 119)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (111, 138)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (112, 122)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (113, 135)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (114, 127)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (115, 131)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (116, 136)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (117, 124)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (118, 132)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (119, 123)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (120, 134)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (121, 126)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (122, 129)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (123, 114)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (124, 113)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (125, 110)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (126, 102)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (127, 105)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (128, 101)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (129, 103)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (130, 107)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (131, 109)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (132, 111)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (133, 115)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (134, 116)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (135, 118)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (136, 117)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (137, 104)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (138, 108)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (139, 112)''',
# '''INSERT INTO CourseBooks (CourseID, BookID) VALUES (140, 106)'''

# ]

# queries = [

# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (101, 237)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (102, 223)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (103, 229)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (104, 201)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (105, 220)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (106, 213)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (107, 224)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (108, 202)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (109, 231)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (110, 216)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (111, 204)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (112, 233)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (113, 207)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (114, 234)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (115, 218)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (116, 221)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (117, 205)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (118, 230)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (119, 210)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (120, 235)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (121, 208)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (122, 236)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (123, 225)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (124, 211)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (125, 227)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (126, 209)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (127, 226)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (128, 203)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (129, 219)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (130, 232)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (131, 214)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (132, 222)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (133, 228)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (134, 212)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (135, 215)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (136, 206)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (137, 238)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (138, 217)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (139, 239)''',
# '''INSERT INTO TeacherCourse (CourseID, TeacherID) VALUES (140, 200)''',

# ]



# for i in queries :
#     cursor.execute(i)



connection.commit()
connection.close()